import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Date;
import java.util.ArrayList;
import java.util.Calendar;

import java.sql.Date;
import java.awt.*;
import javax.swing.*;
import java.sql.Timestamp;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.table.DefaultTableModel;

import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;

import java.util.*;
import java.sql.*; 


import java.text.DateFormat;
import java.text.SimpleDateFormat;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Kashish Gujral
 */
public final class RoomSchedulerFrame extends javax.swing.JFrame {

    /**
     * Creates new form RoomSchedulerFrame
     */
    public RoomSchedulerFrame() {
        initComponents();
        // Load the combo boxes with data.
        rebuildFacultyComboBoxes();
        rebuildDatesComboBoxes();
        rebuildStatusComboBoxes();
        rebuildCheckFacultycombobox();
        rebuildAllRooms();
        loadDates();
    }
    public void loadDates()
    {
        java.sql.Date sdate = new java.sql.Date(Calendar.getInstance().getTime().getTime());
        addDate.setText(sdate.toString());
        dateTxt.setText(sdate.toString());
    }

    public void rebuildFacultyComboBoxes() {
        reserveFacultyComboBox.setModel(new javax.swing.DefaultComboBoxModel(Faculty.getFacultyList().toArray()));
        facultycombostatusbox.setModel(new javax.swing.DefaultComboBoxModel(Faculty.getFacultyList().toArray()));
       
    }

    public void rebuildAllRooms() {
        RoomComboBox.setModel(new javax.swing.DefaultComboBoxModel(RoomQueries.getAllRooms().toArray()));
    }

    public void rebuildCheckFacultycombobox() {
        facultyComboBox.setModel(new javax.swing.DefaultComboBoxModel(Faculty.getFacultyList().toArray()));
    }

    public void rebuildDatesComboBoxes() {
        reserveDateComboBox.setModel(new javax.swing.DefaultComboBoxModel(Dates.getAllDates().toArray()));
    }

    public void rebuildStatusComboBoxes() {
        DateReservation.setModel(new javax.swing.DefaultComboBoxModel(Dates.getAllDates().toArray()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        addFacultyTextField = new javax.swing.JTextField();
        addFacultyButton = new javax.swing.JButton();
        addFacultyStatusLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        reserveFacultyComboBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        reserveDateComboBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        reserveSeatsTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        reserveStatusLabel = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        DateReservation = new javax.swing.JComboBox<>();
        reservationStatusButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        statusText = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        facultyComboBox = new javax.swing.JComboBox<>();
        CancelButton = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        CancelArea = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        dateTxt = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        DropRoomLabel = new javax.swing.JLabel();
        DropButton = new javax.swing.JButton();
        RoomComboBox = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        DropRoomArea = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        AddDateButton = new javax.swing.JButton();
        DateLabel = new javax.swing.JLabel();
        addDate = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        facultycombostatusbox = new javax.swing.JComboBox<>();
        CheckStatusButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        WaitlistStatusArea = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        ReservationStatusAreas = new javax.swing.JTextArea();
        jPanel8 = new javax.swing.JPanel();
        ROOMTEXT = new javax.swing.JLabel();
        RoomTextField = new javax.swing.JTextField();
        ROOMLABEL = new javax.swing.JLabel();
        SeatsTextField = new javax.swing.JTextField();
        RoomSubmitButton = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        ROOMAREA = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Room Scheduler");

        jLabel2.setText("Faculty Name: ");

        addFacultyButton.setForeground(new java.awt.Color(204, 0, 0));
        addFacultyButton.setText("Submit");
        addFacultyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFacultyButtonActionPerformed(evt);
            }
        });

        addFacultyStatusLabel.setText("  ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addFacultyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(addFacultyStatusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(68, 68, 68)
                .addComponent(addFacultyButton)
                .addContainerGap(201, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(addFacultyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addFacultyButton))
                .addGap(57, 57, 57)
                .addComponent(addFacultyStatusLabel)
                .addContainerGap(267, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add Faculty", jPanel1);

        jLabel3.setText("Faculty: ");

        jLabel4.setText("Date: ");

        jLabel5.setText("Seats Required: ");

        jButton1.setForeground(new java.awt.Color(204, 0, 0));
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        reserveStatusLabel.setText("   ");

        jButton2.setText("Refresh");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(reserveSeatsTextField))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(50, 50, 50)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(reserveFacultyComboBox, 0, 106, Short.MAX_VALUE)
                                    .addComponent(reserveDateComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jButton1))
                    .addComponent(reserveStatusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 268, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(reserveFacultyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(reserveDateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(reserveSeatsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reserveStatusLabel)
                .addContainerGap(215, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Reserve Room", jPanel2);

        jLabel6.setText("Date: ");

        reservationStatusButton.setText("Check Reservation Status");
        reservationStatusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservationStatusButtonActionPerformed(evt);
            }
        });

        statusText.setColumns(20);
        statusText.setRows(5);
        jScrollPane1.setViewportView(statusText);

        jLabel12.setText("Faculty");

        jLabel13.setText("Date");

        CancelButton.setText("Submit");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        CancelArea.setColumns(20);
        CancelArea.setRows(5);
        jScrollPane7.setViewportView(CancelArea);

        jButton3.setText("Refresh");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(facultyComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dateTxt)))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(CancelButton)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(DateReservation, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jScrollPane7)
                            .addComponent(reservationStatusButton, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(155, 155, 155)
                .addComponent(jButton3)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(DateReservation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addComponent(reservationStatusButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(facultyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(dateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(CancelButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Reservations", jPanel3);

        DropRoomLabel.setText("Room");

        DropButton.setText("Drop");
        DropButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DropButtonActionPerformed(evt);
            }
        });

        RoomComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        DropRoomArea.setColumns(20);
        DropRoomArea.setRows(5);
        jScrollPane3.setViewportView(DropRoomArea);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(DropRoomLabel)
                        .addGap(18, 18, 18)
                        .addComponent(RoomComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(DropButton))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(371, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DropRoomLabel)
                    .addComponent(RoomComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(DropButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(182, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Drop Room", jPanel5);

        AddDateButton.setText("Check Status");
        AddDateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddDateButtonActionPerformed(evt);
            }
        });

        DateLabel.setText("Date: ");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(AddDateButton)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(DateLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addDate, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(368, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DateLabel)
                    .addComponent(addDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddDateButton)
                .addContainerGap(309, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add Date", jPanel6);

        jLabel9.setText("Faculty");

        facultycombostatusbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        CheckStatusButton.setText("Check Status");
        CheckStatusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckStatusButtonActionPerformed(evt);
            }
        });

        jLabel10.setText("Reservation Status");

        jLabel11.setText("Waitlist Status");

        WaitlistStatusArea.setColumns(20);
        WaitlistStatusArea.setRows(5);
        jScrollPane4.setViewportView(WaitlistStatusArea);

        ReservationStatusAreas.setColumns(20);
        ReservationStatusAreas.setRows(5);
        jScrollPane5.setViewportView(ReservationStatusAreas);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9)
                        .addGap(38, 38, 38)
                        .addComponent(facultycombostatusbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(CheckStatusButton))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
                            .addComponent(jScrollPane4))))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(facultycombostatusbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CheckStatusButton)
                .addGap(26, 26, 26)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(94, 94, 94))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))))
        );

        jTabbedPane1.addTab("Status ", jPanel7);

        ROOMTEXT.setText("Room ");

        ROOMLABEL.setText("Seats");

        RoomSubmitButton.setText("Submit");
        RoomSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoomSubmitButtonActionPerformed(evt);
            }
        });

        ROOMAREA.setColumns(20);
        ROOMAREA.setRows(5);
        jScrollPane6.setViewportView(ROOMAREA);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(RoomSubmitButton))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ROOMLABEL)
                            .addComponent(ROOMTEXT))
                        .addGap(58, 58, 58)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(SeatsTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                            .addComponent(RoomTextField)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(77, 322, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ROOMTEXT)
                    .addComponent(RoomTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ROOMLABEL)
                    .addComponent(SeatsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RoomSubmitButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(208, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add Room", jPanel8);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reservationStatusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservationStatusButtonActionPerformed
        // TODO add your handling code here:rebuildDateComboBoxes();

        ArrayList<String> rooms = new ArrayList<>();
        ArrayList<String> faculty = new ArrayList<>();
        ArrayList<ReservationEntry> reservationList = new ArrayList<>();
        String date = (DateReservation.getSelectedItem().toString());
        reservationList = ReservationQueries.getReservationsByDate(date);
        rooms = ReservationQueries.getRoomsReservedByDate(date);
        faculty = ReservationQueries.getFacultybyReservedDates(date);
        statusText.setText("");
        for (int i = 0; i < reservationList.size(); i++) {
            statusText.append(faculty.get(i) + "reserves room" + rooms.get(i) + "\n");
        }

    }//GEN-LAST:event_reservationStatusButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        String name = reserveFacultyComboBox.getSelectedItem().toString();
        String date = (reserveDateComboBox.getSelectedItem().toString());
        String seatText = reserveSeatsTextField.getText();
        int seats = Integer.parseInt(seatText);
        java.sql.Timestamp currentTimestamp = new java.sql.Timestamp(Calendar.getInstance().getTime().getTime());

        ArrayList<String> reseveredRooms = ReservationQueries.getRoomsReservedByDate(date);
        ArrayList<String> possibleRooms = RoomQueries.getAllPossibleRooms(seats);
        for (String room : possibleRooms) {

            if (!reseveredRooms.contains(room)) {
                ReservationQueries.addReservationEntry(name, room, date, seats, currentTimestamp);
                reserveStatusLabel.setText(name + " has reserved room " + room);//set status
                return;

            }
        }
        //enter waitlist
        WaitlistQueries.addWaitlistEntry(name, date, seats, currentTimestamp);
        reserveStatusLabel.setText(name + " has been added to waitlist for " + seats + " seats");//status

    }//GEN-LAST:event_jButton1ActionPerformed

    private void addFacultyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFacultyButtonActionPerformed
        // TODO add your handling code here:
        String name = addFacultyTextField.getText();
        Faculty.addFaculty(name);
        addFacultyStatusLabel.setText(name + " has been added to the faculty.");

        // rebuild the reservation faculty combo box.
        rebuildFacultyComboBoxes();
        rebuildCheckFacultycombobox();

    }//GEN-LAST:event_addFacultyButtonActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        // TODO add your handling code here:
        String name = facultyComboBox.getSelectedItem().toString();
        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");  
        String date= formatter.format(dateTxt.getText());  
        java.sql.Timestamp currentTimestamp = new java.sql.Timestamp(Calendar.getInstance().getTime().getTime());
        //ArrayList<ReservationEntry> reserve=ReservationQueries.getReservationsByFaculty(name);
        ArrayList<String> faculty = ReservationQueries.getFacultybyReservedDates(date);
        //String roomname=reserve.get(0).getRoom();
        //int seats=RoomQueries.getCapacityForRooms(roomname);
        ArrayList<WaitlistEntry> waitlist = new ArrayList<>();
        waitlist = WaitlistQueries.getWaitlistByDate();

        if (faculty.contains(name) == true) {
            ArrayList<ReservationEntry> reserve = ReservationQueries.getReservationsByFaculty(name);
            String roomname = reserve.get(0).getRoom();
            int seats = RoomQueries.getCapacityForRooms(roomname);
            ReservationQueries.cancelReservation(name, date);
            CancelArea.append(name + " on " + date + " gets cancelled");
            for (int i = 0; i < waitlist.size(); i++) {

                if (date.compareTo(waitlist.get(i).toString()) == 0 & waitlist.get(i).getSeats() <= seats) {
                    WaitlistQueries.cancelWaitlistEntry(waitlist.get(i).getFaculty(), date);
                    ReservationQueries.addReservationEntry(waitlist.get(i).getFaculty(), roomname, waitlist.get(i).toString(), waitlist.get(i).getSeats(), currentTimestamp);
                    CancelArea.append("\n");
                    CancelArea.append("\n" + waitlist.get(i).getFaculty() + " gets room " + roomname + " reserved");
                    break;
                } else {
                };
            }

        } else {
            WaitlistQueries.cancelWaitlistEntry(name, date);
            CancelArea.setText(name + " gets cancelled from waitlist");
        }

    }//GEN-LAST:event_CancelButtonActionPerformed

    private void RoomSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoomSubmitButtonActionPerformed
        // TODO add your handling code here:
        String name = RoomTextField.getText();
        String seats = SeatsTextField.getText();
        int seats_number = Integer.parseInt(seats);
        RoomQueries.addRoom(name, seats_number);
        ROOMAREA.setText(name + " room added" + "\n");
        java.sql.Timestamp currentTimestamp = new java.sql.Timestamp(Calendar.getInstance().getTime().getTime());
        ArrayList<WaitlistEntry> waitlist = new ArrayList<>();
        waitlist = WaitlistQueries.getWaitlistByDate();
        for (int i = 0; i < waitlist.size(); i++) {
            if (waitlist.get(i).getSeats() <= seats_number) {
                ArrayList<String> reservedrooms = ReservationQueries.getRoomsReservedByDate(waitlist.get(i).toString());
                if (!reservedrooms.contains(name)) {
                    WaitlistQueries.cancelWaitlistEntry(waitlist.get(i).getFaculty(), waitlist.get(i).toString());
                    ReservationQueries.addReservationEntry(waitlist.get(i).getFaculty(), name, waitlist.get(i).toString(), waitlist.get(i).getSeats(), currentTimestamp);
                    ROOMAREA.append(waitlist.get(i).getFaculty() + " reserves " + name + " for " + waitlist.get(i).toString());
                    ROOMAREA.append("\n");

                }
            }
        }
        //ROOMAREA.replaceSelection("");    
        rebuildAllRooms();
        // ROOMAREA.setText(null);
    }//GEN-LAST:event_RoomSubmitButtonActionPerformed

    private void DropButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DropButtonActionPerformed
        // TODO add your handling code here:
        String roomname = RoomComboBox.getSelectedItem().toString();
        RoomQueries.dropRoom(roomname);
        DropRoomArea.setText("room " + roomname + " has been dropped");
        ArrayList<ReservationEntry> droppedReservations = ReservationQueries.getReservationsByRoom(roomname);
        ReservationQueries.deleteReservation(roomname);

        //  ArrayList<String> reservedrooms=ReservationQueries.getRoomsReserved();
        java.sql.Timestamp currentTimestamp = new java.sql.Timestamp(Calendar.getInstance().getTime().getTime());

        for (int i = 0; i < droppedReservations.size(); i++) {
            // fsculty date seats
            // use date to get reservations
            boolean booked = false;
            String date = droppedReservations.get(i).toString();
            ArrayList<String> reseveredRooms = ReservationQueries.getRoomsReservedByDate(date);
            int seats = droppedReservations.get(i).getSeats();
            ArrayList<String> possibleRooms = RoomQueries.getAllPossibleRooms(seats);
            for (String room : possibleRooms) {

                if (!reseveredRooms.contains(room)) { // check for that date room
                    ReservationQueries.addReservationEntry(droppedReservations.get(i).getFaculty(), room, droppedReservations.get(i).toString(), droppedReservations.get(i).getSeats(), currentTimestamp);
                    DropRoomArea.append("\n");
                    DropRoomArea.append(droppedReservations.get(i).getFaculty() + " " + droppedReservations.get(i).getDate() + " is moved to waitlist");
                    DropRoomArea.append("\n");
                    DropRoomArea.append(droppedReservations.get(i).getFaculty() + " reserves" + " room " + room + " on" + droppedReservations.get(i).getDate() + " from waitlist");
                    DropRoomArea.append("\n");
                    booked = true;
                    return;
                } else {
                }
            }
            if (booked == false) {
                WaitlistQueries.addWaitlistEntry(droppedReservations.get(i).getFaculty(), droppedReservations.get(i).toString(), droppedReservations.get(i).getSeats(), currentTimestamp);
                DropRoomArea.append("\n");
                DropRoomArea.append(droppedReservations.get(i).getFaculty() + " " + droppedReservations.get(i).getDate() + " is moved to waitlist");
                DropRoomArea.append("\n");

            }

        }
        rebuildAllRooms();


    }//GEN-LAST:event_DropButtonActionPerformed

    private void CheckStatusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckStatusButtonActionPerformed
        // TODO add your handling code here:
        String name = facultycombostatusbox.getSelectedItem().toString();
        ArrayList<String> waitlist = WaitlistQueries.getWaitlistofAllFacultys();
        ArrayList<ReservationEntry> reservationlist = new ArrayList<>();
        ArrayList<String> facultyReservationList = ReservationQueries.getFacultyOnReservationList();
        if (facultyReservationList.contains(name) && waitlist.contains(name)) {
            reservationlist = ReservationQueries.getReservationsByFaculty(name);
            ReservationStatusAreas.setText("Reservation status for ");

            for (int i = 0; i < reservationlist.size(); i++) {
                ReservationStatusAreas.append("\n");
                ReservationStatusAreas.append(reservationlist.get(i).getFaculty() + " reserved room " + reservationlist.get(i).getRoom() + " on " + reservationlist.get(i).getDate());
                ReservationStatusAreas.append("\n");
            }
            ArrayList<WaitlistEntry> waitlist_faculty = new ArrayList<>();
            waitlist_faculty = WaitlistQueries.getWaitlistByFaculty(name);
            for (int j = 0; j < waitlist_faculty.size(); j++) {
                WaitlistStatusArea.setText("Waitlist status for");
                WaitlistStatusArea.append("\n");
                WaitlistStatusArea.append(waitlist_faculty.get(j).getFaculty() + " wailisted on " + waitlist_faculty.get(j).getDate());
                WaitlistStatusArea.append("\n");

            }

        } else {
            if (facultyReservationList.contains(name)) {
                reservationlist = ReservationQueries.getReservationsByFaculty(name);
                ReservationStatusAreas.setText("Reservation status for ");
                WaitlistStatusArea.setText("");
                ReservationStatusAreas.append("\n");

                for (int i = 0; i < reservationlist.size(); i++) {
                    ReservationStatusAreas.append("\n");
                    ReservationStatusAreas.append(reservationlist.get(i).getFaculty() + " reserved room " + reservationlist.get(i).getRoom() + " on " + reservationlist.get(i).getDate());
                    ReservationStatusAreas.append("\n");

                }
            } else {
                ArrayList<WaitlistEntry> waitlist_faculty = new ArrayList<>();
                waitlist_faculty = WaitlistQueries.getWaitlistByFaculty(name);
                for (int j = 0; j < waitlist_faculty.size(); j++) {
                    WaitlistStatusArea.setText("Waitlist status for");
                    WaitlistStatusArea.append("\n");
                    WaitlistStatusArea.append(waitlist_faculty.get(j).getFaculty() + " waitlisted on " + waitlist_faculty.get(j).getDate());
                    WaitlistStatusArea.append("\n");

                }
            }
        }


    }//GEN-LAST:event_CheckStatusButtonActionPerformed

    private void AddDateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddDateButtonActionPerformed
        Dates dt=new Dates();
        
        dt.addDate(addDate.getText());
    }//GEN-LAST:event_AddDateButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      reserveDateComboBox.setModel(new javax.swing.DefaultComboBoxModel(Dates.getAllDates().toArray()));
      facultyComboBox.setModel(new javax.swing.DefaultComboBoxModel(Faculty.getFacultyList().toArray()));
      
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        reserveDateComboBox.setModel(new javax.swing.DefaultComboBoxModel(Dates.getAllDates().toArray()));
        reserveFacultyComboBox.setModel(new javax.swing.DefaultComboBoxModel(Faculty.getFacultyList().toArray()));

    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RoomSchedulerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RoomSchedulerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RoomSchedulerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RoomSchedulerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RoomSchedulerFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddDateButton;
    private javax.swing.JTextArea CancelArea;
    private javax.swing.JButton CancelButton;
    private javax.swing.JButton CheckStatusButton;
    private javax.swing.JLabel DateLabel;
    private javax.swing.JComboBox<String> DateReservation;
    private javax.swing.JButton DropButton;
    private javax.swing.JTextArea DropRoomArea;
    private javax.swing.JLabel DropRoomLabel;
    private javax.swing.JTextArea ROOMAREA;
    private javax.swing.JLabel ROOMLABEL;
    private javax.swing.JLabel ROOMTEXT;
    private javax.swing.JTextArea ReservationStatusAreas;
    private javax.swing.JComboBox<String> RoomComboBox;
    private javax.swing.JButton RoomSubmitButton;
    private javax.swing.JTextField RoomTextField;
    private javax.swing.JTextField SeatsTextField;
    private javax.swing.JTextArea WaitlistStatusArea;
    private javax.swing.JTextField addDate;
    private javax.swing.JButton addFacultyButton;
    private javax.swing.JLabel addFacultyStatusLabel;
    private javax.swing.JTextField addFacultyTextField;
    private javax.swing.JTextField dateTxt;
    private javax.swing.JComboBox<String> facultyComboBox;
    private javax.swing.JComboBox<String> facultycombostatusbox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton reservationStatusButton;
    private javax.swing.JComboBox<String> reserveDateComboBox;
    private javax.swing.JComboBox<String> reserveFacultyComboBox;
    private javax.swing.JTextField reserveSeatsTextField;
    private javax.swing.JLabel reserveStatusLabel;
    private javax.swing.JTextArea statusText;
    // End of variables declaration//GEN-END:variables
}
